name: Multi-OS Package Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, temp]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: alma9
            image: almalinux:9
            code: el9
            repo: alma
            folder: packages
            script: .github/scripts/rpm/alma/9.sh

          - name: debian12
            image: debian:12
            code: bookworm
            repo: debian
            folder: packages
            script: .github/scripts/deb/debian/12.sh

          - name: ubuntu2404
            image: ubuntu:24.04
            code: noble
            repo: ubuntu
            folder: packages
            script: .github/scripts/deb/ubuntu/24.04.sh

    container:
      image: ${{ matrix.image }}
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from VERSION file
        id: version
        run: echo "RAWEB_WEBSERVER_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: /ngx
          key: ${{ matrix.name }}-ngx-deps-${{ env.NGINX_VERSION }}-${{ env.SYSTEM_PCRE }}-${{ env.NGX_MOD_MODSECURITY }}-${{ env.NGX_MOD_HEADERS_MORE }}-${{ env.NGX_MOD_GEOIP2 }}-${{ env.BORINGSSL_VERSION }}-v2
          restore-keys: |
            ${{ matrix.name }}-ngx-deps-${{ env.NGINX_VERSION }}-${{ env.SYSTEM_PCRE }}-${{ env.NGX_MOD_MODSECURITY }}-${{ env.NGX_MOD_HEADERS_MORE }}-${{ env.NGX_MOD_GEOIP2 }}-
            ${{ matrix.name }}-ngx-deps-${{ env.NGINX_VERSION }}-${{ env.SYSTEM_PCRE }}-${{ env.NGX_MOD_MODSECURITY }}-${{ env.NGX_MOD_HEADERS_MORE }}-
            ${{ matrix.name }}-ngx-deps-${{ env.NGINX_VERSION }}-${{ env.SYSTEM_PCRE }}-${{ env.NGX_MOD_MODSECURITY }}-
            ${{ matrix.name }}-ngx-deps-${{ env.NGINX_VERSION }}-${{ env.SYSTEM_PCRE }}-
            ${{ matrix.name }}-ngx-deps-${{ env.NGINX_VERSION }}-
            ${{ matrix.name }}-ngx-deps-

      - name: Run Build Script
        run: |
          chmod +x ${{ matrix.script }}
          ${{ matrix.script }}
        env:
          BUILD_NAME: ${{ matrix.name }}
          BUILD_IMAGE: ${{ matrix.image }}
          BUILD_CODE: ${{ matrix.code }}
          BUILD_REPO: ${{ matrix.repo }}
          BUILD_FOLDER: ${{ matrix.folder }}
          UPLOAD_USER: ${{ secrets.UPLOAD_USER }}
          UPLOAD_PASS: ${{ secrets.UPLOAD_PASS }}
          BUILD_CORES: '70'
          DOMAIN: 'de.repo.raweb.al'
          NGX_WORK_FOLDER: '/ngx'
          RAWEB_WEBSERVER_VERSION: ${{ env.RAWEB_WEBSERVER_VERSION }}
          # https://nginx.org/en/download.html
          NGINX_VERSION: '1.29.0'
          # https://github.com/PCRE2Project/pcre2/releases
          SYSTEM_PCRE: '10.45'
          # https://github.com/owasp-modsecurity/ModSecurity-nginx/releases
          NGX_MOD_MODSECURITY: '1.0.4'
          # https://github.com/openresty/headers-more-nginx-module/tags
          NGX_MOD_HEADERS_MORE: '0.39'
          # https://github.com/leev/ngx_http_geoip2_module/releases
          NGX_MOD_GEOIP2: '3.4'
          # https://github.com/google/boringssl/releases
          BORINGSSL_VERSION: '0.20250701.0'